FROM quay.io/school21/alpine:3.16

RUN apk --no-cache --upgrade add \
    git \
    git-lfs \
    curl \
    jq \
    bash \
    build-base \
    python3 \
    valgrind \
    cppcheck \
    alpine-sdk \
    pcre-dev \
    check-dev \
    subunit-dev \
    clang-extra-tools

WORKDIR /project

COPY . /project

CMD ["make", "test"]
